title: ʕ•ᴥ•ʔ BearPrint
description: A tiny local-first print server that lets you send text from your phone or laptop to a USB-connected thermal printer — no cloud required.
theme: jekyll-theme-minimal
