name: Release Bearprint API Binaries

on:
  push:
    tags:
      - 'bearprint-api-v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        working-directory: ./bearprint-api
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o bearprint-api-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bearprint-api-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bearprint-api/bearprint-api-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: |
            artifacts/**/*
